<script lang="ts">
  const fakeGeneratedReports = [
    { name: "Monthly Revenue - June 2025", date: "2025-07-01", by: "Admin" },
    { name: "Subscriber Growth Q2 2025", date: "2025-07-01", by: "Admin" },
    { name: "Plan Distribution Analysis", date: "2025-06-15", by: "Admin" },
    {
      name: "Complaint Resolution Times - May 2025",
      date: "2025-06-05",
      by: "Admin",
    },
  ];
</script>

<div class="space-y-8">
  <div>
    <h1 class="text-3xl font-bold text-gray-800">Reports Center</h1>
    <p class="mt-1 text-gray-500">Generate and download operational reports.</p>
  </div>

  <div class="bg-white p-6 rounded-lg shadow-md">
    <h3 class="text-lg font-semibold text-gray-800 mb-2">Quick Reports</h3>
    <p class="text-sm text-gray-500 mb-4">Open pre-built reports.</p>
    <a
      href="/reports/monthly-billing"
      class="inline-flex items-center rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700"
    >
      Monthly Billing
    </a>
  </div>

  <!-- Report Generation Section -->
  <div class="bg-white p-6 rounded-lg shadow-md">
    <h3 class="text-lg font-semibold text-gray-800 mb-4">
      Generate a New Report
    </h3>
    <div class="flex flex-wrap items-end gap-4">
      <div class="flex-grow">
        <label for="report-type" class="block text-sm font-medium text-gray-700"
          >Report Type</label
        >
        <select
          id="report-type"
          class="mt-1 block w-full p-2 border border-gray-300 rounded-md bg-white focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
        >
          <option disabled selected>Choose a report...</option>
          <option>Monthly Revenue</option>
          <option>Subscriber Growth</option>
          <option>Plan Distribution Analysis</option>
          <option>Complaint Resolution Times</option>
        </select>
      </div>
      <button
        class="bg-indigo-600 text-white font-bold py-2 px-4 rounded-md hover:bg-indigo-700 flex items-center gap-2"
      >
        <!-- Fake Download Icon -->
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-2 w-2"
          viewBox="0 0 20 20"
          fill="currentColor"
        >
          <path
            fill-rule="evenodd"
            d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z"
            clip-rule="evenodd"
          />
        </svg>
        Generate & Download
      </button>
    </div>
  </div>

  <!-- Generated Reports History -->
  <div class="bg-white p-6 rounded-lg shadow-md">
    <h3 class="text-lg font-semibold text-gray-800 mb-4">
      Generated Reports History
    </h3>
    <div class="overflow-x-auto">
      <table class="w-full text-left text-sm">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
          <tr>
            <th class="px-4 py-3">Report Name</th>
            <th class="px-4 py-3">Date Generated</th>
            <th class="px-4 py-3">Generated By</th>
            <th class="px-4 py-3">Actions</th>
          </tr>
        </thead>
        <tbody>
          {#each fakeGeneratedReports as report}
            <tr class="border-b hover:bg-gray-50">
              <td class="px-4 py-3 font-medium">{report.name}</td>
              <td class="px-4 py-3">{report.date}</td>
              <td class="px-4 py-3">{report.by}</td>
              <td class="px-4 py-3">
                <a
                  href="#"
                  on:click|preventDefault
                  class="text-indigo-600 hover:text-indigo-800 font-medium flex items-center gap-1"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-4 w-4"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    ><path
                      fill-rule="evenodd"
                      d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z"
                      clip-rule="evenodd"
                    /></svg
                  >
                  Download
                </a>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  </div>
</div>
